name: invo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  pdf: ^3.11.3  
  printing: ^5.11.1
  pdf_image_renderer: ^1.0.1
  path_provider: ^2.1.5 
  flutter_pdfview: ^1.4.0
  share_plus: ^10.1.4
  open_file: ^3.5.10
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSansBengali-Regular.ttf

  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
